version: 2

models:
  - name: games_with_points
    description: "Raw games data with points for home vs away team"
    columns:
      - name: game_id
        data_tests:
          - unique
          - not_null

  - name: home_away_agg
    description: "Summary of a teams home and away points"
    columns:
      - name: team_id
        data_tests:
          - unique
          - not_null

  - name: team_gplus
    alias: team_goals_added
    description: "This is a clean version of the raw.team_goals_added"

  - name: teams_clean
    description: "The teams information including ids and conference "
    columns:
      - name: team_id
        data_tests:
          - unique
          - not_null